version: "3.9"
services:
  app:
    build: .
    restart: "always"
    ports:
      - "7777:7777"
    depends_on:
      - mongodb
    env_file:
      - .env
    networks:
      - virtual-bartender
  mongodb:
    image: mongo:latest
    volumes:
      - mongo:/data/db
    ports:
      - "27017:27017"
    networks:
      - virtual-bartender
  react-app:
    build: ./client
    stdin_open: true
    restart: "always"
    ports: 
      - "3000:3000"
    depends_on: 
      - app
    networks:
      - virtual-bartender
volumes:
  mongo:
    driver: local
networks:
  virtual-bartender:
    driver: bridge
