version: "3.9"
services:
  app:
    build: .
    restart: "always"
    ports:
      - "7777:7777"
    depends_on:
      - mongodb
    env_file:
      - .env
  mongodb:
    image: mongo:latest
    volumes:
      - mongo:/data/db
    ports:
      - "27017:27017"
volumes:
  mongo:
    driver: local
