version: "3.9"
services:
  app:
    build: .
    restart: "always"
    ports:
      - "7777:7777"
    env_file:
      - .env
    networks:
      - virtual-bartender
  react-app:
    build: ./client
    stdin_open: true
    restart: "always"
    ports: 
      - "3000:3000"
    depends_on: 
      - app
    networks:
      - virtual-bartender
networks:
  virtual-bartender:
    driver: bridge
